---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp1gcr
 labels:
   app: myapp1gcr
spec:
 replicas: 2
 selector:
  matchLabels:
   app: myapp1gcr
 template:
  metadata:
   labels:
    app: myapp1gcr
  spec:
   containers:
   - name: myapp1gcr
     image: eu.gcr.io/refined-engine-262020/krushnapadhy/myapp1gcr:tagversion
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
 name: myapp1gcr
spec:
 type: LoadBalancer
 selector:
  app: myapp1gcr
 ports:
  - protocol: TCP
    port: 5602
    targetPort: 8080